import unittest
import urllib.request

import constants
from logger import CallerLogs
from serviceCaller import *
logger = CallerLogs.createServiceUTLogger()


#Dictionaries for comparing after UT execution.
dct_output = {'urls': [{'url_link': 'http://127.0.0.1:5000/urlinfo/100/10.10.1.35:10535/one/two?id=44&name=ankur', 'is_malware': 'True', 'error': False, 'url_id': 100}, {'url_link': 'http://127.0.0.1:5000/urlinfo/101/10.10.1.36:10536/one/two?id=44&name=ank2', 'is_malware': 'False', 'error': False, 'url_id': 101}, {'url_link': 'http://127.0.0.1:5000/urlinfo/102/10.10.1.37:10537/one/two?id=44&name=ank3', 'is_malware': 'False', 'error': False, 'url_id': 102}, {'url_link': 'http://127.0.0.1:5000/urlinfo/103/10.10.1.38:10538/one/two?id=44&name=ank4', 'is_malware': 'False', 'error': False, 'url_id': 103}, {'url_link': 'http://127.0.0.1:5000/urlinfo/101/10.10.1.36:10536/one/three?id=46&name=saurabh', 'is_malware': 'True', 'error': False, 'url_id': 101}, {'url_link': 'http://127.0.0.1:5000/urlinfo/102/10.10.1.37:10537/two/three?id=14&name=munni', 'is_malware': 'True', 'error': False, 'url_id': 102}, {'url_link': 'http://127.0.0.1:5000/urlinfo/103/10.10.1.38:10538/one/four?id=56&name=punit', 'is_malware': 'True', 'error': False, 'url_id': 103}, {'desc': 'Invalid url ankur/...', 'url_link': 'http://127.0.0.1:5000/ankur/', 'error': True}]}

dct_all_malware = {'records': [[100, '10.10.1.35', 10535, 'one/two', 'id=44&name=ankur'], [101, '10.10.1.36', 10536, 'one/three', 'id=46&name=saurabh'], [102, '10.10.1.37', 10537, 'two/three', 'id=14&name=munni'], [103, '10.10.1.38', 10538, 'one/four', 'id=56&name=punit'], [104, '10.10.1.39', 10539, 'three/four', 'id=45&name=seena']]}

dct_fake_url = {'error': 'Invalid url some/fake/url/...'}



class ServiceCaller(unittest.TestCase):
    def test_first(self):
        logger.info("running test_first test")
        mem = getMemorySize()
        self.assertEqual(mem, 1024)
        logger.info("test completed successfully")

    def test_second(self):
        logger.info("running test_second test")
        FILENAME = 'test_urls.txt'
        dct = {}
        dct['urls'] = []
        openFileAndLoadUrls(constants.TEST_FILENAME, dct)
        self.assertEqual(dct,dct_output)
        logger.info("test completed successfully")

    def test_third(self):
        logger.info("running test_third test")
        url = "http://127.0.0.1:5000/all/malwares/"
        resp = urllib.request.urlopen(url)
        all_malware_info = eval(resp.read())
        self.assertEqual(all_malware_info, dct_all_malware)
        logger.info("test completed successfully")

    def test_fourth(self):
        logger.info("running test_fourth test")
        url = "http://127.0.0.1:5000/some/fake/url/"
        resp = urllib.request.urlopen(url)
        fake_url = eval(resp.read())
        self.assertEqual(fake_url, dct_fake_url)
        logger.info("test completed successfully")

    def test_fifth(self):
        logger.info("running test_fifth test")
        url = "http://127.0.0.1:5000/urlinfo/101/10.10.1.36:10536/one/three?id=46&name=saurabh"
        resp = urllib.request.urlopen(url)
        url_info = eval(resp.read())
        self.assertEqual(url_info.get("is_malware"), "True")
        logger.info("test completed successfully")

    def test_sixth(self):
        logger.info("running test_sixth test")
        url = "http://127.0.0.1:5000/urlinfo/101/10.10.1.36:10536/one/three?id=46&name=ankur"
        resp = urllib.request.urlopen(url)
        url_info = eval(resp.read())
        self.assertEqual(url_info.get("is_malware"), "False")
        logger.info("test completed successfully")

    def test_seveth(self):
        '''
          Invalid port range test
          {"error":"invalid port range..."}
        :return:
        '''
        logger.info("running test_seveth test")
        url = "http://127.0.0.1:5000/urlinfo/144/10.10.1.35:65536/one/two"
        resp = urllib.request.urlopen(url)
        url_info = eval(resp.read())
        output = url_info.get("error")
        self.assertEqual(output, constants.INVALID_PORT_RANGE)
        logger.info("test completed successfully")

    def test_eighth(self):
        '''
        Invalid url due to missing hostname
        {"error":"incomplete or invalid url..."}
        :return:
        '''
        logger.info("running test_eighth test")
        url = "http://127.0.0.1:5000/urlinfo/144/:10535/one/two?id=44&name=ank45"
        resp = urllib.request.urlopen(url)
        url_info = eval(resp.read())
        output = url_info.get("error")
        self.assertEqual(output, constants.INCOMPLETE_URL)
        logger.info("test completed successfully")

    def test_nineth(self):
        '''
        Invalid url due to missing port
        {"error":"incomplete or invalid url..."}
        :return:
        '''
        logger.info("running test_nineth test")
        url = "http://127.0.0.1:5000/urlinfo/144/10.10.1.35:/one/two?id=44&name=ank45"
        resp = urllib.request.urlopen(url)
        url_info = eval(resp.read())
        output = url_info.get("error")
        self.assertEqual(output, constants.INCOMPLETE_URL)
        logger.info("test completed successfully")

    def test_tenth(self):
        '''
        Invalid url due to missing hostname and port
        {"error":"incomplete or invalid url..."}
        :return:
        '''
        logger.info("running test_tenth test")
        url = "http://127.0.0.1:5000/urlinfo/144/:/one/two?id=44&name=ank45"
        resp = urllib.request.urlopen(url)
        url_info = eval(resp.read())
        output = url_info.get("error")
        self.assertEqual(output, constants.INCOMPLETE_URL)
        logger.info("test completed successfully")

    def test_twelfth(self):
        '''
        Invalid url due to invalid ID
        {"error":"Invalid url urlinfo/abc/10.10.1.35:10535/one/two..."}
        :return:
        '''
        logger.info("running test_twelfth test")
        url = "http://127.0.0.1:5000/urlinfo/abc/10.10.1.35:10535/one/two?id=44&name=ank45"
        resp = urllib.request.urlopen(url)
        url_info = eval(resp.read())
        output = url_info.get("error")
        self.assertEqual(output, constants.INVALID_PATH_DESC)
        logger.info("test completed successfully")

    def test_thirteenth(self):
        '''
        Invalid url due to missing id
        {"error":"Invalid url urlinfo//10.10.1.35:10535/one/two..."}
        :return:
        '''
        logger.info("running test_thirteenth test")
        url = "http://127.0.0.1:5000/urlinfo//10.10.1.35:10535/one/two?id=44&name=ank45"
        resp = urllib.request.urlopen(url)
        url_info = eval(resp.read())
        output = url_info.get("error")
        self.assertEqual(output, constants.MISSING_ID)
        logger.info("test completed successfully")

if __name__== "__main__":
    unittest.main()